language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38

install:
  - python -m pip install -r requirements.txt
  - python -m pip install -e .

script:
  - make test-py
  - make format
  - test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
