name: CI tests

on: [push, pull_request]

jobs:

  Run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install -r requirements.txt

    - name: Check formatting
      run: source .github/workflows/format.sh

    - name: Test
      run: source .github/workflows/test.sh
